// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oegjwvpiyifmfkaxpmht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZ2p3dnBpeWlmbWZrYXhwbWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTIzMTMsImV4cCI6MjA3MDI4ODMxM30.U00ReVufY6rsEiowY83nC4p4vEebe_LjUxSf9txS1Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});